
app:
  mysql-server: localhost

spring.jpa.hibernate.ddl-auto: update

spring.datasource:
  url: jdbc:mysql://localhost:3306/employeedb
  username: sa
  password: sa

spring.datasource.hikari.initializationFailTimeout: 60000

---
spring.profiles: docker

app:
  mysql-server: database